//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/Input/UserInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @UserInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @UserInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""UserInput"",
    ""maps"": [
        {
            ""name"": ""MainAction"",
            ""id"": ""6955be47-d63c-4e4d-91af-f8d057a25110"",
            ""actions"": [
                {
                    ""name"": ""ToggleMenus"",
                    ""type"": ""Button"",
                    ""id"": ""e6c1b1d8-81cf-4459-b02b-b79b656d48f1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5d4e560d-e6f4-421f-9fd7-aa9ee44b5af1"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleMenus"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""219da0eb-1509-4e37-960b-9faa529ce5e6"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleMenus"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // MainAction
        m_MainAction = asset.FindActionMap("MainAction", throwIfNotFound: true);
        m_MainAction_ToggleMenus = m_MainAction.FindAction("ToggleMenus", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // MainAction
    private readonly InputActionMap m_MainAction;
    private List<IMainActionActions> m_MainActionActionsCallbackInterfaces = new List<IMainActionActions>();
    private readonly InputAction m_MainAction_ToggleMenus;
    public struct MainActionActions
    {
        private @UserInput m_Wrapper;
        public MainActionActions(@UserInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @ToggleMenus => m_Wrapper.m_MainAction_ToggleMenus;
        public InputActionMap Get() { return m_Wrapper.m_MainAction; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MainActionActions set) { return set.Get(); }
        public void AddCallbacks(IMainActionActions instance)
        {
            if (instance == null || m_Wrapper.m_MainActionActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MainActionActionsCallbackInterfaces.Add(instance);
            @ToggleMenus.started += instance.OnToggleMenus;
            @ToggleMenus.performed += instance.OnToggleMenus;
            @ToggleMenus.canceled += instance.OnToggleMenus;
        }

        private void UnregisterCallbacks(IMainActionActions instance)
        {
            @ToggleMenus.started -= instance.OnToggleMenus;
            @ToggleMenus.performed -= instance.OnToggleMenus;
            @ToggleMenus.canceled -= instance.OnToggleMenus;
        }

        public void RemoveCallbacks(IMainActionActions instance)
        {
            if (m_Wrapper.m_MainActionActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMainActionActions instance)
        {
            foreach (var item in m_Wrapper.m_MainActionActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MainActionActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MainActionActions @MainAction => new MainActionActions(this);
    public interface IMainActionActions
    {
        void OnToggleMenus(InputAction.CallbackContext context);
    }
}
